### PR TITLE
Added findKing function.

### PR DESCRIPTION
**Pull request by D-Studios**
I added the findKing function on the backend.js. This function is essential in determining if the game has already been won or not. In this modified chess game, the game ends when one of the kings are captured (instead of checkmated). To find out if the current player's king has been captured, this function loops through the entire board and tries to find the player's king.

### CODE REVIEW

**Comment by NickPerlich** [comment]
Looks good, @D-Studios! The code is well commented and not unnecessarily complex.

**Comment by BPond4** [comment]
It may be less efficient than having a check whenever a piece is moved to see if the king is captured that way. However, for this kind of implementation, this seems very clean and clear and seems to function correctly.

**Comment by kevinci-03** [comment]
Simple implementation but gets the job done, great function!

**Comment by D-Studios** [comment]
> It may be less efficient than having a check whenever a piece is moved to see if the king is captured that way. However, for this kind of implementation, this seems very clean and clear and seems to function correctly.

It is true that my approach is not the most efficient. However, since the worst case scenario is looping 64 tiles at every turn, my approach would still be acceptable. If there were a variable number of tiles I had to loop through - or a large constant amount - then my approach would probably become problematic.

**Comment by D-Studios** [comment]
> Looks good, @D-Studios! The code is well commented and not unnecessarily complex.

Thanks!

**Comment by D-Studios** [comment]
> Simple implementation but gets the job done, great function!

Thanks!

**Pull request merged**
